### ISSUE TITLE
会津若松市と郡山市が抜けている

### ISSUE THREAD

**Issue by mapconcierge** [amx-project/kuwanauchi07fukushima#1]
いわきが出てこない症状が見えているとのこと

要確認

**Comment by hfu** [comment]
確かに、xml フォルダには 07204（いわき市の市区町村コード）で始まるファイルが見当たりません。ファイルが抜けているようです。

**Comment by hfu** [comment]
いわき市のみ、コミュニティ内部の共有用ドライブから取り出せたのでアップしました。ファイルの共有ありがとうございます。
https://github.com/amx-project/kuwanauchi07fukushima/commit/f466b3d282209fa692cfe37739477cd92a666bef

07202～07024が抜けているようなので、まだアップロードできていない都市があるかもしれません。

**Comment by hfu** [comment]
余裕ができたので、どこが抜けているのか調べてみました。

- [x] 福島市 07201
- [x] 会津若松市07202
- [x] 郡山市07203
- [x] いわき市07204

現在、まだ含めることができていないのは、会津若松市と郡山市ですね。イシューのタイトルも変更しておきます。

**Comment by hfu** [comment]
アップロードしました！ https://github.com/amx-project/kuwanauchi07fukushima/commit/2f6d8b38de3beca268d4fd6776a655277a2fecb9

**Comment by mapconcierge** [comment]
ありがとうございます！！！
